config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :chats, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment,presence:true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @comment = BookComment.find(params[:id])
    @book = @comment.book
    @comment.destroy
    # redirect_back(fallback_location: root_path)
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comments.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td><%= link_to(book_comment.user) do %>
        <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, remote:true, class: "btn btn-sm btn-danger" %></td>
    <% end %>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$('#book_comments_<%= @book.id %>').html("<%= j(render 'book_comments/book_comments', book: @book) %>");
$("text_area").val("");
$("#comment").val("");
$(".comment_count").html("コメント数:<%= @book.book_comments.count %>")

app/views/book_comments/destroy.js.erb
$('#book_comments_<%= @book.id %>').html("<%= j(render 'book_comments/book_comments', book: @book) %>");
$(".comment_count").html("コメント数:<%= @book.book_comments.count %>")